# Generated by Django 4.2.6 on 2023-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], max_length=100),
        ),
    ]
